### ISSUE TITLE
On authenticate, if no user exists in the local db with a matching href, create it

### ISSUE THREAD

**Issue by laser** [stormpath/stormpath-rails#22]
When calling 

```ruby
x = ModelClass.authenticate('someusername', 'somepassword')
```

It is possible that Stormpath successfully authenticated (that is, returned an Account resource corresponding to the provided username and password) but no model existed in your local database with a matching "stormpath_url." In this event, persist a new model into the database with a "stormpath_url" matching the Account resource's href.

**Comment by omgitstom** [comment]
This issue is obsolete with the new rails repo.  Feel free to check it out and let us know if you have any issues
