### ISSUE TITLE
Programmatically create application (and a directory associated as a login source) during test runs

### ISSUE THREAD

**Issue by laser** [stormpath/stormpath-rails#23]
The reliance on APPLICATION_URL as a value set in your ENV hash causes a variety of problems:

1. the developer must provision an application and directory (and assign that directory as a login source to the application) before running tests
1. VCR cassettes cannot be committed to VCS because each developer's APPLICATION_URL will be different (and the cassettes are matched to the requests by URI and HTTP method)

This work is deferred pending the development (on the Stormpath API side) of a way to auto-create a directory when creating an application.

**Comment by omgitstom** [comment]
You can always modify the configuration to use a hardcoded url instead in version 1.1.x of stormpath-rails.  let me know if you have any questions.  Closing this for now
