### ISSUE TITLE
rails generate stormpath:install hangs

### ISSUE THREAD

**Issue by gthorsen** [stormpath/stormpath-rails#31]
The rails generate stormpath:install hangs command just hangs.

ruby 2.1.1p76
Rails 4.2.4
RubyGems 2.2.2
Mac OS 10.10

Wondering if this is a known bug.

Thanks.

**Comment by nikone** [comment]
It seems as a common problem with spring
http://stackoverflow.com/questions/25027284/ruby-on-rails-console-hanging-when-loading

can you please try to restart spring

**Comment by DamirSvrtan** [comment]
Closing as we weren't getting any feedback. Also, 2.0 version of the Rails integration is out now.
