### ISSUE TITLE
rails generate stormpath:install doesn't work

### ISSUE THREAD

**Issue by xuloo** [stormpath/stormpath-rails#33]
Ruby 2.2.2
Rails 4.2.4

running
```
rails generate stormpath:install
```

results in the following stacktrace.

/Users/trevor/.rvm/gems/ruby-2.2.2/gems/stormpath-rails-0.4.2/lib/stormpath/rails/account.rb:3:in `include': wrong argument type Class (expected Module) (TypeError)
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/stormpath-rails-0.4.2/lib/stormpath/rails/account.rb:3:in `<top (required)>'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/stormpath-rails-0.4.2/lib/stormpath-rails.rb:1:in `require'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/stormpath-rails-0.4.2/lib/stormpath-rails.rb:1:in `block in <top (required)>'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/stormpath-rails-0.4.2/lib/stormpath-rails.rb:1:in `each'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/stormpath-rails-0.4.2/lib/stormpath-rails.rb:1:in `<top (required)>'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Users/trevor/Documents/projects/general/stormpath/config/application.rb:7:in `<top (required)>'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/application.rb:82:in `require'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/application.rb:82:in `preload'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/application.rb:143:in `serve'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/application.rb:131:in `block in run'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/application.rb:125:in `loop'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/application.rb:125:in `run'
	from /Users/trevor/.rvm/gems/ruby-2.2.2/gems/spring-1.4.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/trevor/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/trevor/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

What versions of Ruby/Rails is this gem compatible with?

**Comment by 0bserver07** [comment]
I had the same issue, after debugging, here is what I found.

The main gem still installs version  `0.4.4`

On their hosted gem section, it says the latest is `1.0.0.beta`


![IMG](http://i58.tinypic.com/2vtd4sm.png)

So the actual latest version is not installed :/ Which should be `v1.1.0.beta`

**Comment by omgitstom** [comment]
https://rubygems.org/gems/stormpath-rails
Has been updated and the readme is updated to explain the install instructions - I am closing this issue, feel free to open another if it is not resolved

**Comment by 0bserver07** [comment]
@omgitstom Thanks, perfect it works!
