### ISSUE TITLE
Please push the most recent gem to the RubyGems site.

### ISSUE THREAD

**Issue by 0bserver07** [stormpath/stormpath-rails#34]
The gem still fetches the old version, 0.4.4, when I downloaded your repo, the gem build is 1.1.0.beta8 or something like that. It would be great to have that on the RubyGems

**Comment by omgitstom** [comment]
Hi @0bserver07 - this should be fixed now and the readme was updated - thanks!

**Comment by 0bserver07** [comment]
@omgitstom thanks!
