### ISSUE TITLE
After successful login, Rails error: NoMethodError - undefined method `id' for nil:NilClass:

### ISSUE THREAD

**Issue by 0bserver07** [stormpath/stormpath-rails#36]
Stacktrace:
```ruby 
NoMethodError - undefined method `id' for nil:NilClass:
  stormpath-rails (1.1.2.beta) lib/stormpath/rails/session.rb:13:in `initialize_session'
  stormpath-rails (1.1.2.beta) app/controllers/stormpath/rails/sessions_controller.rb:9:in `create'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
```
1. gem install works  :+1:
2. rails stormpath generator works √
3. copied this over:
```ruby 
<% if signed_in? %>
  <%= current_user.email %>
  <%= button_to "Sign out", sign_out_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", sign_in_path %>
<% end %>
```
* User logs in, then on return back to the site: I get that error.  Is there an extra parameter I need to set in the config file?

![img](http://i58.tinypic.com/2qalmr5.jpg)

**Comment by omgitstom** [comment]
Hi @0bserver07 - The developer will look into this tomorrow - thanks for your patience!

**Comment by nikone** [comment]
Hi @0bserver07 tnx for the feedback. 

When user signed in his account was found on Stormpath but wasn't found in the local database(via email). Each time user registers his account is created on Stormpath servers and there is also a record in the local database. 

Did you maybe deleted the user on the local database manually after he was registered? this would explain why there is an active Stormpath account but no record in DB.

**Comment by 0bserver07** [comment]
Hwy @nikone thanks for the reply, I'm not sure if that's how I thought it works.

So in order for this to work:
1. User with same email have to login to the Rails app.
2. Then login to stormpath
and it will work,

Any guide on how this structure should look like?

**Comment by cha55son** [comment]
I'm running into this issue as well. I don't think this gem can assume that the stormpath user is also in the local database. For example, we have an app where users are added, via third parties, into stormpath. There is no way to create an account through the app itself.

Therefore I would expect this gem to do the following upon login:

* Ensure the user is a valid enabled user in stormpath.
* Check the DB for that user
    * If the user exists, continue
    * Otherwise, create the user
* Handle sessions for the user

**Comment by cha55son** [comment]
Here's my monkeypatch to fix this issue:

```ruby
class SessionsController < Stormpath::Rails::SessionsController

    def create
        result = authenticate user_from_params

        if result.success?
            account = result.response.account
            @user = User.find_or_create_by(email: account.email) do |user|
                user.given_name = account.given_name
                user.surname = account.surname
            end

            if @user.errors.empty?
                reset_session # http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
                initialize_session(@user)
                redirect_to configuration.login.next_uri, notice: 'Successfully signed in'
            else
                set_flash_message :error, "There was an error validating your account."
                render template: "sessions/new"
            end
        else
            set_flash_message :error, result.error_message
            render template: "sessions/new"
        end
    end
end

# Monkeypatch the status so we can access the sdk result.
module Stormpath
    module Rails
        class AuthenticationStatus
            attr_accessor :response
        end
    end
end
```

**Comment by tomvalorsa** [comment]
Had the same problem with something I'm trying to build. I want several apps to work off the same Stormpath account directory and I only want to be able to sign people up through my admin dashboard for the time being. Thanks for the fix, @cha55son!

**Comment by DamirSvrtan** [comment]
glad everybody found a fix to this issue. The new Rails integration version 2.0.0 is a complete rewrite and doesn't persist any account data in the local database. If needed, it supports a way to persist that by manually overwriting the registration controller.
