### ISSUE TITLE
NoMethodError in Stormpath::Rails::SessionsController#crate

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-rails#39]
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

Rails 4.2.5

![46220b61-cff8-4a1c-9ab4-b220cc2a10c5](https://cloud.githubusercontent.com/assets/3199093/12131930/b3fdb50a-b3cb-11e5-88b6-229f31b7d92d.png)

![47b05a2f-4ffe-47d6-baf2-be5a32520187](https://cloud.githubusercontent.com/assets/3199093/12131996/5cb026ec-b3cc-11e5-8e24-18275c41c6b7.png)

**Comment by DamirSvrtan** [comment]
Was the old integration, we are out with 2.0.0. now. Closing because it's not relevant anymore.
