### ISSUE TITLE
uninitialized constant Stormpath::Generators::InstallGenerator::ApplicationController

### ISSUE THREAD

**Issue by adnguyen1989** [stormpath/stormpath-rails#40]
I am getting the following error when running `rails generate stormpath:install` on Ruby 2.1.1, Mac Yosemite. Any idea?

```
/Users/jackof1trade/Downloads/stormpath-rails-master/lib/generators/stormpath/install/install_generator.rb:17:in `inject_stormpath_into_application_controller': uninitialized constant Stormpath::Generators::InstallGenerator::ApplicationController (NameError)

**Comment by nikone** [comment]
Hi @adnguyen1989 I couldn't reproduce your error. Can you please post which version of stormpath-rails are you using? From what you posted It seems you cloned the gem to stormpath-rails-master in your Downloads folder, which is ok but can you please check the version.

**Comment by adnguyen1989** [comment]
@nikone sorry for the late reply. I started with another project and getting a separate issue. Will create a new issue.
