### ISSUE TITLE
undefined method `login=' for #<Stormpath::Rails::UserConfig::Login:0x007f89f0e644f8> (NoMethodError)

### ISSUE THREAD

**Issue by rubenrails** [stormpath/stormpath-rails#41]
If I add this block of config to my application:

```ruby
Stormpath::Rails.configure do |config|
  config.login do |c|
    c.login = true
  end
end
```

I get the following error:
`undefined method login=' for #<Stormpath::Rails::UserConfig::Login:0x007f89f0e644f8> (NoMethodError)`

I don't think that config line is even needed, should README be updated to remove that part of the config?

**Comment by nikone** [comment]
yea, I needed to update the readme. the login option is replaced with enabled option (which is true by default).

```ruby
Stormpath::Rails.configure do |config|
  config.login do |c|
    c.enabled = false
  end
end
```

Feel free to ask if you have additional questions regarding this or if you think we can improve the readme

**Comment by rubenrails** [comment]
Awesome, thanks for clarifying and updating docs, @nikone.
