### ISSUE TITLE
Include `Rails` namespace when overriding an stormpath controller.

### ISSUE THREAD

**Issue by rubenrails** [stormpath/stormpath-rails#42]
When overriding a given controller, as noted in the README, it should include the `Rails` namespace.

According to README: `class UsersController < Stormpath::UsersController
`
**Actual override**: `class UsersController < Stormpath::Rails::UsersController
`

Same for `Sessions` and `Passwords` controllers.

**Comment by nikone** [comment]
Tnx @rubenrails Documentation is fixed.

**Comment by rubenrails** [comment]
Thanks @nikone :+1:
