### ISSUE TITLE
`method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x007fe0c0b439c8>

### ISSUE THREAD

**Issue by adnguyen1989** [stormpath/stormpath-rails#43]
I am using stormpath with Rails 5 (--api mode) and Ruby 2.2.3

Gemfile
```
gem 'stormpath-rails', '~> 1.1', '>= 1.1.2.beta'
```

On running rails generate stormpath:install I am getting the following error

```
/Users/jackof1trade/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.beta2/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x007fe0c0b439c8>
Did you mean?  asset_host (NoMethodError)
```

UPDATE: if I unpack the gem, remove the assets.precompile line from config/initializer/assets.rb, I can run the command successfully. 

But then I run into a separate issue, helper_method undefined for lib/stormpath/rails/social.rb and session.rb

**Comment by omgitstom** [comment]
Hi @adnguyen1989,

I was talking the engineer about this and this is a problem with Stormpath gem and Rails 5.  Since Rails 5 is still in beta, we are not going to adding support for it until it is in its final version and released.

I'm going to keep this issue open for the meantime, there is some good information in here.

Thanks for the report!
Tom

**Comment by mathieujobin** [comment]
I am getting this error in 2 or 17 cucumber scenarios of cucumber-rails gem
any news on this ? rails app is not `--api` 

why would it work 15 out of 17 ?

https://travis-ci.org/cucumber/cucumber-rails/jobs/142780215

**Comment by houmanka** [comment]
A quick question, Now the Rails 5 is release will you be updating this? 
```
`method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x007feed712b3d0>
Did you mean?  asset_host (NoMethodError)
```
Still happening!

**Comment by DamirSvrtan** [comment]
I've tried it out and it works. Released in 2.0.0.

**Comment by mathieujobin** [comment]
@houmanka you are missing sprockets, either the gem is not loaded or disabled in config/application.rb
or if you don't want it, you need to update your config/environments/* files

good luck

**Comment by mathieujobin** [comment]
for those using cucumber-rails, you need my fork which should get merged before xmas
its ready
