### ISSUE TITLE
Undefined local variable or method `new_register_path`

### ISSUE THREAD

**Issue by clthck** [stormpath/stormpath-rails#49]
Undefined local variable or method `new_register_path` error raises when register function is disabled.
I think it'd better check whether register is enabled or not and then render/do not render register link accordingly.

**Comment by DamirSvrtan** [comment]
Hey @clthck, thnx for reporting this bug. A new version of the gem is released (2.0.1) with this fix.

**Comment by clthck** [comment]
👍
