### ISSUE TITLE
Write sanity check tests for path links depending on what the configuration is

### ISSUE THREAD

**Issue by DamirSvrtan** [stormpath/stormpath-rails#50]
As #49 says, we got an error when a developer would disable the register flow - the path helper for a new registration on the login path would blow up.

I've fixed that now, but we need take care of similar cases such:

login link on register form when login is disabled.
forgot password link on login form when login is disabled.
login link on forgot password form.

**Comment by cilim** [comment]
Please review: https://github.com/stormpath/stormpath-rails/pull/52
