### ISSUE TITLE
can't run most commands other than rails s when stormpath_rails_routes is in routes.rb

### ISSUE THREAD

**Issue by szehnder** [stormpath/stormpath-rails#61]
I am able to boot the rails application w/ stormpath-rails in the gem file and routes.rb.  

However, I can't run any other command (e.g. rake, or bundle exec rails g, etc)
```
bundle exec rails g model foo
```

Gives the following output

```
/Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/http/authc/sauthc1_signer.rb:88:in `+': no implicit conversion of nil into String (TypeError)
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/http/authc/sauthc1_signer.rb:88:in `sign_request'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/http/http_client_request_executor.rb:32:in `execute_request'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/data_store.rb:128:in `execute_request'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/data_store.rb:56:in `get_resource'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/resource/associations.rb:68:in `get'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/client.rb:39:in `tenant'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-sdk-1.1.5/lib/stormpath-sdk/resource/associations.rb:43:in `block in has_many'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/config/application_resolution.rb:67:in `app_from_name'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/config/application_resolution.rb:20:in `app'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/config/dynamic_configuration.rb:16:in `app'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/config/dynamic_configuration.rb:43:in `proccess_account_store_verification'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/config/dynamic_configuration.rb:9:in `initialize'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/configuration.rb:24:in `new'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/configuration.rb:24:in `block in config_object'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/configuration.rb:23:in `tap'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/configuration.rb:23:in `config_object'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/configuration.rb:19:in `web'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/router.rb:25:in `block in stormpath_rails_routes'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:997:in `block in constraints'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:859:in `scope'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:997:in `constraints'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/stormpath-rails-2.0.1/lib/stormpath/rails/router.rb:24:in `stormpath_rails_routes'
	from /Users/szehnder/Dropbox/Keto Business/git/hotmess-svc/config/routes.rb:6:in `block in <top (required)>'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/szehnder/Dropbox/Keto Business/git/hotmess-svc/config/routes.rb:1:in `<top (required)>'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/activesupport-5.0.0.1/lib/active_support/file_update_checker.rb:77:in `call'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/activesupport-5.0.0.1/lib/active_support/file_update_checker.rb:77:in `execute'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/szehnder/Dropbox/Keto Business/git/hotmess-svc/config/environment.rb:5:in `<top (required)>'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/spring-2.0.0/lib/spring/application.rb:92:in `require'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/spring-2.0.0/lib/spring/application.rb:92:in `preload'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /Users/szehnder/.rvm/gems/ruby-2.2.4@keto-svc/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/szehnder/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by szehnder** [comment]
By the way I'm on Rails 5.0.0.1 and ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]

**Comment by cilim** [comment]
Thank you for submitting this issue @szehnder.

We will try and replicate it using the same Ruby and Rails version and let you know the outcome.

**Comment by cilim** [comment]
@szehnder I created a new Rails 5 application (Rails 5.0.0.1) and am using Ruby 2.3.1p112 and all is working as expected.

Please check out your ``config/stormpath.yml`` file and add your application href in it like so:

```
stormpath:
  application:
    href: <%= ENV['STORMPATH_APPLICATION_URL'] %>
    name: Stormpath Example App
```

if you're using environment variables. If not, you can just paste your application url too:

```
stormpath:
  application:
    href: https://api.stormpath.com/v1/applications/__app_href_id__
    name: null
```

**Comment by szehnder** [comment]
Ok, still having issues.  Is there a better place to request support for this, or should I keep posting my issues here?

sean

**Comment by szehnder** [comment]
thanks for your help!

**Comment by szehnder** [comment]
I started over (completely fresh ruby, rails, etc. install), and am still having issues.
[foo2.zip](https://github.com/stormpath/stormpath-rails/files/540535/foo2.zip)

Note: I am using figaro, so you'll need to put your api key and secret in config/application.yml

Also, I removed my stormpath app name/url from config/stormpath.yml so you'll need to put in yours there to test.

After you have those items updated / working try the following a few times (fails for me intermittently):
``
bundle exec rails g model foo
``
if you get the above to work, then try:
``
bundle exec rails destroy model foo
``
this also periodically fails for me -- altho just by running it a few times I am able to usually get it to work.

Then the following doesn't work for me at all (same as my original error posting above) if I have the routes.rb showing "stormpath_rails_routes"

``
bundle exec railroady -M -o models.dot
``

If I comment out "stormpath_rails_routes" in routes.rb that same command works fine.

I believe it's not specifically that railroady command that has the problem, because I've seen the same issue when I'm trying other things like rails generators or rake commands.

**Comment by cilim** [comment]
I downloaded your foo2.zip file, ran bundle install, migrated the database and seeds, adjusted my application url, client_id and client_secret for Stormpath, generated and destroyed a bunch of foo3, foo4, foo5 models and successfully ran the ``railroady`` command. All of that with the ``stormpath_rails_routes`` defined in my routes file. Also, I made sure that when the ``rails server`` is up and running that localhost:3000/login works.

The only thing that the terminal informed me was:

```
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
```

After running `gem install bundler` all was working as expected.

[foo-61.zip](https://github.com/stormpath/stormpath-rails/files/541124/foo-61.zip)

Make sure you export the environment variables correctly in your `.bashrc` or `.zshrc` file, depending on what you use.

```
export STORMPATH_API_KEY_ID=someapikeyid
export STORMPATH_API_KEY_SECRET=correspondingapiketsecret
export STORMPATH_APPLICATION_URL=https://api.stormpath.com/v1/applications/_your_application_id
```

**Comment by cilim** [comment]
@szehnder any progress?

**Comment by leoamigood** [comment]
got same error with foo-61.zip 
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]

/Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/http/authc/sauthc1_signer.rb:88:in `+': no implicit conversion of nil into String (TypeError)
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/http/authc/sauthc1_signer.rb:88:in `sign_request'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/http/http_client_request_executor.rb:32:in `execute_request'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/data_store.rb:145:in `execute_request'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/data_store.rb:57:in `get_resource'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/resource/associations.rb:68:in `get'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/client.rb:39:in `tenant'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-sdk-1.4.0/lib/stormpath-sdk/resource/associations.rb:43:in `block in has_many'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/application_resolution.rb:41:in `client_applications'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/application_resolution.rb:37:in `client_has_exactly_two_applications?'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/application_resolution.rb:29:in `automatic_resolution'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/application_resolution.rb:22:in `app'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/dynamic_configuration.rb:26:in `app'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/dynamic_configuration.rb:67:in `proccess_account_store_verification'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/config/dynamic_configuration.rb:19:in `initialize'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/configuration.rb:24:in `new'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/configuration.rb:24:in `block in config_object'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/configuration.rb:23:in `tap'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/configuration.rb:23:in `config_object'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/configuration.rb:19:in `web'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/router.rb:31:in `block in stormpath_rails_routes'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:997:in `block in constraints'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:859:in `scope'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:997:in `constraints'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/stormpath-rails-2.3.0/lib/stormpath/rails/router.rb:30:in `stormpath_rails_routes'
	from /Users/leo/RubymineProjects/foo-61/config/routes.rb:3:in `block in <top (required)>'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/leo/RubymineProjects/foo-61/config/routes.rb:1:in `<top (required)>'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/activesupport-5.0.0.1/lib/active_support/file_update_checker.rb:77:in `execute'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/leo/.rvm/gems/ruby-2.3.3@global/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/leo/RubymineProjects/foo-61/config/environment.rb:5:in `<top (required)>'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/application.rb:92:in `require'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/application.rb:92:in `preload'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /Users/leo/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/leo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
