### ISSUE TITLE
/forgot does not redirect to IDSite when its enabled.

### ISSUE THREAD

**Issue by saimaddali** [stormpath/stormpath-rails#85]
If I have IDSite enabled, and go to localhost:3000/forgot, the regular forgot password page is displayed. Expected behavior is that I should be redirected to tenantname.id.stormpath.io/forgot and NOT localhost:3000/forgot. To sum it up, the following works:

localhost:3000/login -> redirects me to IDSite -> Click on Forgot Password -> redirect to tenantname.id.stormpath.io/forgot

The following doesn't:
localhost:3000/forgot -> regular forgot page rendered and not IDSite. 

Fix: 
When /forgot is requested an IDSite JWT needs to be constructed and the user should be redirected to tenantname.id.stormpath.io/forgot

**Comment by cilim** [comment]
@saimaddali thank you for submitting this issue. I'll start working on a fix asap.

**Comment by cilim** [comment]
@saimaddali the pull request with the fix has been merged to master: https://github.com/stormpath/stormpath-rails/pull/86/files

A new version of the gem has been released. Please run `bundle update stormpath-rails` and make sure the version `2.6.0` is installed.
